/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opus_OpusSupport */

#ifndef _Included_opus_OpusSupport
#define _Included_opus_OpusSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opus_OpusSupport
 * Method:    nativeIsOpusFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_opus_OpusSupport_nativeIsOpusFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     opus_OpusSupport
 * Method:    nativeOpenOpusFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_opus_OpusSupport_nativeOpenOpusFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     opus_OpusSupport
 * Method:    nativeCloseOpusFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opus_OpusSupport_nativeCloseOpusFile
  (JNIEnv *, jclass);

/*
 * Class:     opus_OpusSupport
 * Method:    nativeGetTotalPcmDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_opus_OpusSupport_nativeGetTotalPcmDuration
  (JNIEnv *, jclass);

/*
 * Class:     opus_OpusSupport
 * Method:    nativeReadOpusFile
 * Signature: (Ljava/nio/ByteBuffer;I[I)V
 */
JNIEXPORT void JNICALL Java_opus_OpusSupport_nativeReadOpusFile
  (JNIEnv *, jclass, jobject, jint, jintArray);

/*
 * Class:     opus_OpusSupport
 * Method:    nativeSeekOpusFile
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_opus_OpusSupport_nativeSeekOpusFile
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
