
android_library(
  name = 'lib',
  srcs = glob(['java/**/*.java']),
  deps = [
    '//modules/auth/res:res',
    '//jars:recyclerview-v7',

    '//modules/utils/res:res',
    '//modules/utils/src:lib',
  ],

  visibility = [ 'PUBLIC' ],
)

project_config(
  src_target = ':lib',
  src_roots = ['java']
)
