/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class webp_SupportBitmapFactory */

#ifndef _Included_webp_SupportBitmapFactory
#define _Included_webp_SupportBitmapFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     webp_SupportBitmapFactory
 * Method:    nativeDecodeBitmap
 * Signature: (Ljava/nio/ByteBuffer;I)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_webp_SupportBitmapFactory_nativeDecodeBitmap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
